/** Entity factories — ported verbatim from ArtymerCockpit.jsx. */
import type {
  Account,
  Company,
  ContentItem,
  DiscoveryCandidate,
  IcpConfig,
  Invoice,
  Project,
  Prospect,
  Supplier,
  Task,
} from "./types";
import { DEFAULT_ICP_SEGMENTS, DEFAULT_SIZE_BANDS } from "./constants";

export const rid = (p: string): string =>
  p + Date.now().toString(36) + Math.random().toString(36).slice(2, 5);

export const today = (): string => new Date().toISOString().slice(0, 10);

export const blankCompany = (): Company => ({
  id: "company",
  migrated: false,
  brand: "Artymer",
  logo: "",
  letterhead: "",
  baseCurrency: "RON",
  fiscal: {
    legalName: "",
    taxId: "",
    regNo: "",
    address: "",
    iban: "",
    bank: "",
    vatRegistered: false,
    // Romania's standard TVA has been 21% since 1 Aug 2025 (Law 141/2025,
    // up from 19%); the reduced rate is 11%. Editable in Settings.
    vatRate: "21",
    series: "ART",
  },
  icp: defaultIcp(),
  // Value of one unit in EUR. RON ≈ 1/5.25 (EUR/RON ~5.25, Aug 2026).
  // These are a starting point only — refresh them in Settings; FX drifts.
  fx: { RON: 0.1906, USD: 0.92 },
  deposit: "30",
  lotFail: "5",
  rework: "2",
  window: "3",
  bufferWeeks: "2",
  weeklyOutreach: "25",
  monthlyRevenue: "5000",
});

export const blankAccount = (): Account => ({
  id: rid("a"),
  name: "",
  type: "Company",
  servicePath: "Commission",
  status: "prospect",
  market: "RO",
  contactName: "",
  contactRole: "",
  email: "",
  phone: "",
  source: "",
  referredBy: "",
  notes: "",
  testimonial: "",
  lastContact: "",
  nextAction: "",
  nextDate: "",
});

export const blankSupplier = (): Supplier => ({
  id: rid("s"),
  name: "",
  status: "Warming",
  platform: "Alibaba",
  leadTime: "",
  moq: "",
  contact: "",
  goldenSamples: "",
  notes: "",
  quality: "",
  communication: "",
  price: "",
  capabilities: "",
});

export const blankInvoice = (accountId = "", projectId = ""): Invoice => ({
  id: rid("inv"),
  kind: "Factură",
  series: "",
  number: "",
  status: "draft",
  accountId,
  projectId,
  currency: "RON",
  issueDate: today(),
  dueDate: "",
  paidDate: "",
  lines: [{ desc: "", qty: "1", unitPrice: "", vat: "0" }],
  notes: "",
  buyer: { name: "", taxId: "", regNo: "", address: "", email: "" },
  seller: { name: "", taxId: "", regNo: "", address: "", email: "" },
});

export const blankContent = (): ContentItem => ({
  id: rid("c"),
  title: "",
  channel: "Instagram",
  status: "idea",
  date: "",
  link: "",
  notes: "",
  projectId: "",
});

export const blankTask = (link: { type?: string; id?: string } = {}): Task => ({
  id: rid("t"),
  title: "",
  due: today(),
  done: false,
  linkType: link.type || "",
  linkId: link.id || "",
  source: "manual",
});

export const blankProject = (accountId = ""): Project => ({
  id: rid("p"),
  schemaV: 2,
  accountId,
  name: "",
  servicePath: "",
  stage: "Proposal",
  lost: false,
  supplierId: "",
  qty: "30",
  unitPrice: "165",
  currency: "EUR",
  deadline: "",
  depositExpected: "",
  balanceExpected: "",
  rev: "1.0",
  maker: "",
  deposit: "",
  lotFail: "",
  rework: "",
  window: "",
  caseRef: "",
  caseMat: "316L",
  caseDia: "",
  caseDiaT: "0.10",
  l2l: "",
  thick: "",
  lugW: "",
  caseFin: "",
  wr: "3 ATM",
  caseNote: "",
  cal: "",
  calFn: "3-hand",
  acc: "±20",
  accUnit: "day",
  handRef: "",
  handLen: "",
  handFin: "",
  lume: "none",
  movementNote: "",
  crysMat: "Sapphire",
  crysShape: "Flat",
  ar: "Inner",
  crysDia: "",
  crysDiaT: "0.10",
  crown: "",
  back: "",
  strap: "",
  crystalNote: "",
  dialMat: "Brass",
  dialDia: "",
  dialDiaT: "0.10",
  dialThk: "0.40",
  dialThkT: "0.05",
  feet: "",
  tex: "None",
  texDepth: "",
  texDepthT: "0.02",
  gloss: "",
  print: "Pad print",
  reg: "0.10",
  marker: "Applied / appliqué",
  markerPos: "0.15",
  markerAtt: "",
  date: "none",
  dialGrad: "Solid",
  dialNote: "",
  colors: [{ name: "", ref: "" }],
  engLoc: "",
  engTxt: "",
  engMethod: "Laser",
  engDepth: "",
  engNote: "",
  center: "0.10",
  align: "0.30",
  clear: "0.10",
  bezel: "0.10",
  wrTest: "3 ATM static, 10 s hold, no ingress",
  clean: "no particle ≥ 0.05 mm under crystal at 10×",
  lumeStd: "even coat, no pooling under 10×",
  pieceName: "",
  edition: "",
  story: "",
  highlights: "",
  lang: "EN",
  images: { hero: "", dial: "", caseImg: "", back: "", clientLogo: "", movementImg: "" },
  files: { movementSpec: "", engravingVector: "" },
  tooling: "",
  cMovement: "",
  cCase: "",
  cDial: "",
  cHands: "",
  cCrystal: "",
  cStrap: "",
  cAssembly: "",
  cPack: "",
  cShip: "",
  cDuty: "",
  cOther: "",
  feePct: "",
  depositPaid: false,
  depositDate: "",
  balancePaid: false,
  balanceDate: "",
  qc: {
    received: false,
    results: {},
    signed: false,
    signedDate: "",
    disabled: [],
    sample: { decision: "", date: "", reviewer: "", notes: "", media: "" },
  },
  warranty: { deliveredDate: "", months: "12", serial: "", services: [] },
});

/* ---- Outbound Engine ------------------------------------------------- */

export const defaultIcp = (): IcpConfig => ({
  segments: DEFAULT_ICP_SEGMENTS.map((s) => ({
    id: rid("seg"),
    name: s.name,
    enabled: true,
    servicePath: s.servicePath,
    signals: s.signals,
    notes: s.notes,
  })),
  cities: ["Miercurea Ciuc", "Odorheiu Secuiesc", "Cluj-Napoca", "Târgu Mureș", "Budapest"],
  sizeBands: [...DEFAULT_SIZE_BANDS],
});

export const blankIcpSegment = (): IcpConfig["segments"][number] => ({
  id: rid("seg"),
  name: "",
  enabled: true,
  servicePath: "Commission",
  signals: "",
  notes: "",
});

export const blankProspect = (): Prospect => ({
  id: rid("pr"),
  name: "",
  org: "",
  role: "",
  segment: "",
  city: "",
  market: "RO",
  lang: "EN",
  channel: "Email",
  email: "",
  phone: "",
  signal: "",
  sourceUrl: "",
  status: "Not Contacted",
  touches: ["", "", "", "", ""],
  log: [],
  notes: "",
  drafts: [],
  accountId: "",
  createdAt: today(),
});

export const blankCandidate = (): DiscoveryCandidate => ({
  id: rid("dc"),
  org: "",
  segment: "",
  city: "",
  market: "RO",
  signal: "",
  signalType: "other",
  sourceUrl: "",
  contactHint: "",
  rationale: "",
  status: "pending",
  createdAt: today(),
  source: "discovery",
  score: null,
});
