/** Entity factories — ported verbatim from ArtymerCockpit.jsx. */
import type { Account, Company, Project, Supplier, Task } from "./types";

export const rid = (p: string): string =>
  p + Date.now().toString(36) + Math.random().toString(36).slice(2, 5);

export const today = (): string => new Date().toISOString().slice(0, 10);

export const blankCompany = (): Company => ({
  id: "company",
  migrated: false,
  brand: "Artymer",
  fx: { RON: 0.2, USD: 0.92 },
  deposit: "30",
  lotFail: "5",
  rework: "2",
  window: "3",
  bufferWeeks: "2",
  weeklyOutreach: "25",
  monthlyRevenue: "5000",
});

export const blankAccount = (): Account => ({
  id: rid("a"),
  name: "",
  type: "Company",
  servicePath: "Commission",
  status: "prospect",
  market: "RO",
  contactName: "",
  contactRole: "",
  email: "",
  phone: "",
  source: "",
  notes: "",
  testimonial: "",
  lastContact: "",
  nextAction: "",
  nextDate: "",
});

export const blankSupplier = (): Supplier => ({
  id: rid("s"),
  name: "",
  status: "Warming",
  platform: "Alibaba",
  leadTime: "",
  moq: "",
  contact: "",
  goldenSamples: "",
  notes: "",
});

export const blankTask = (link: { type?: string; id?: string } = {}): Task => ({
  id: rid("t"),
  title: "",
  due: today(),
  done: false,
  linkType: link.type || "",
  linkId: link.id || "",
  source: "manual",
});

export const blankProject = (accountId = ""): Project => ({
  id: rid("p"),
  schemaV: 2,
  accountId,
  name: "",
  servicePath: "",
  stage: "Proposal",
  lost: false,
  supplierId: "",
  qty: "30",
  unitPrice: "165",
  currency: "EUR",
  deadline: "",
  depositExpected: "",
  balanceExpected: "",
  rev: "1.0",
  maker: "",
  deposit: "",
  lotFail: "",
  rework: "",
  window: "",
  caseRef: "",
  caseMat: "316L",
  caseDia: "",
  caseDiaT: "0.10",
  l2l: "",
  thick: "",
  lugW: "",
  caseFin: "",
  wr: "3 ATM",
  cal: "",
  calFn: "3-hand",
  acc: "±20",
  accUnit: "day",
  handRef: "",
  handLen: "",
  handFin: "",
  lume: "none",
  crysMat: "Sapphire",
  crysShape: "Flat",
  ar: "Inner",
  crysDia: "",
  crysDiaT: "0.10",
  crown: "",
  back: "",
  strap: "",
  dialMat: "Brass",
  dialDia: "",
  dialDiaT: "0.10",
  dialThk: "0.40",
  dialThkT: "0.05",
  feet: "",
  tex: "None",
  texDepth: "",
  texDepthT: "0.02",
  gloss: "",
  print: "Pad print",
  reg: "0.10",
  marker: "Applied / appliqué",
  markerPos: "0.15",
  markerAtt: "",
  date: "none",
  colors: [{ name: "", ref: "" }],
  engLoc: "",
  engTxt: "",
  engMethod: "Laser",
  engDepth: "",
  center: "0.10",
  align: "0.30",
  clear: "0.10",
  bezel: "0.10",
  wrTest: "3 ATM static, 10 s hold, no ingress",
  clean: "no particle ≥ 0.05 mm under crystal at 10×",
  lumeStd: "even coat, no pooling under 10×",
  pieceName: "",
  edition: "",
  story: "",
  highlights: "",
  lang: "EN",
  images: { hero: "", dial: "", caseImg: "", back: "", clientLogo: "" },
  tooling: "",
  cMovement: "",
  cCase: "",
  cDial: "",
  cAssembly: "",
  cPack: "",
  cShip: "",
  cDuty: "",
  cOther: "",
  depositPaid: false,
  depositDate: "",
  balancePaid: false,
  balanceDate: "",
  qc: { received: false, results: {}, signed: false, signedDate: "", disabled: [] },
});
